EventName = 'Seeing the Invisible'
Logo = '../static/images/gyc-logo-hotspot.svg'
QrUrlPrefix = 'https://events.sangana.co/download/'

[[CardFields]]
Name = 'Full Name'
Template = '{{.NameFirst}} {{.NameLast}}'

[[CardFields]]
Name = 'Registration Type'
Template = '{{.EventPass}}'

[[CardFields]]
Name = 'T-Shirt Size'
Template = '{{if .ShirtSize}}{{.ShirtSize}}{{else}}No Shirt{{end}}'

[[Meals]]
Name = 'Thursday Breakfast'
Slug = 'thursday_breakfast'

[[Meals]]
Name = 'Thursday Lunch'
Slug = 'thursday_lunch'

[[Meals]]
Name = 'Friday Breakfast'
Slug = 'friday_breakfast'

[[Meals]]
Name = 'Sabbath Breakfast'
Slug = 'sabbath_breakfast'

[[Meals]]
Name = 'Sabbath Lunch'
Slug = 'sabbath_lunch'

[[Meals]]
Name = 'Sunday Breakfast'
Slug = 'sunday_breakfast'

[[ExtraScans]]
Name = 'T-Shirt Distribution'
Slug = 'tshirt_distribution'
Unique = true
Test = "ShirtSize != '' && ShirtSize != 'No Shirt'"
AllowMsg = '{{.NameFirst}} {{.NameLast}} can receive {{.ShirtSize}} t-shirt'
DenyMsg = '{{.NameFirst}} {{.NameLast}} did not order a t-shirt'
DuplicateMsg = '{{.NameFirst}} {{.NameLast}} already received their {{.ShirtSize}} t-shirt {{.MinutesAgo}} minutes ago'
VariantField = 'ShirtSize'


[EventPassMapping]
exhibitorPass = 'Exhibitor'
option1 = 'Full Conference - Adult'
option2 = 'Full Conference - Minor'
sabbathOnly = 'Sabbath Only'

[RegistrantDisplay]
[[RegistrantDisplay.FieldGroups]]
Name = 'Personal Information'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'DisplayId'
Label = 'ID'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'NameFirst'
Label = 'First Name'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'NameLast'
Label = 'Last Name'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'date_of_birth'
Label = 'Date of Birth'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'FirstTime'
Label = 'First Time Attendee'

[[RegistrantDisplay.FieldGroups]]
Name = 'Meals'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.thursday_breakfast'
Label = 'Thursday Breakfast'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.thursday_lunch'
Label = 'Thursday Lunch'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.thursday_supper'
Label = 'Thursday Supper'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.friday_breakfast'
Label = 'Friday Breakfast'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.friday_lunch'
Label = 'Friday Lunch'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.friday_supper'
Label = 'Friday Supper'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.sabbath_breakfast'
Label = 'Sabbath Breakfast'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.sabbath_lunch'
Label = 'Sabbath Lunch'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.sabbath_supper'
Label = 'Sabbath Supper'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.sunday_breakfast'
Label = 'Sunday Breakfast'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Meals.sunday_lunch'
Label = 'Sunday Lunch'

[[RegistrantDisplay.FieldGroups]]
Name = 'Registration Details'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'EventPass'
Label = 'Registration Type'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'GroupId'
Label = 'Group'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'ShirtSize'
Label = 'T-Shirt Size'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'RegistrationReason'
Label = 'Why Are You Attending?'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'Subtext'
Label = 'Location'

[[RegistrantDisplay.FieldGroups]]
Name = 'Address'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'address_country'
Label = 'Country'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'address_state'
Label = 'State/Province'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'address_city'
Label = 'City'

[[RegistrantDisplay.FieldGroups.Fields]]
Key = 'address_zip'
Label = 'ZIP/Postal Code'
