EventName = 'Seeing the Invisible'
Logo = '../static/images/gyc-logo-hotspot.svg'

[EventPassMapping]
sabbathOnly = "Sabbath Only"
exhibitorPass = "Exhibitor"
option1 = "Full Conference - Adult"
option2 = "Full Conference - Minor"

[[CardFields]]
Name = 'Full Name'
Template = '{{.NameFirst}} {{.NameLast}}'

[[CardFields]]
Name = 'Registration Type'
Template = '{{.EventPass}}'

[[CardFields]]
Name = 'T-Shirt Size'
Template = '{{if .ShirtSize}}{{.ShirtSize}}{{else}}No Shirt{{end}}'

[[Meals]]
Name = 'Thursday Breakfast'
Slug = 'thursday_breakfast'

[[Meals]]
Name = 'Thursday Lunch'
Slug = 'thursday_lunch'

[[Meals]]
Name = 'Friday Breakfast'
Slug = 'friday_breakfast'

[[Meals]]
Name = 'Sabbath Breakfast'
Slug = 'sabbath_breakfast'

[[Meals]]
Name = 'Sabbath Lunch'
Slug = 'sabbath_lunch'

[[Meals]]
Name = 'Sunday Breakfast'
Slug = 'sunday_breakfast'

[[ExtraScans]]
Name = 'T-Shirt Distribution'
Slug = 'tshirt_distribution'
Unique = true
Test = "ShirtSize != '' && ShirtSize != 'No Shirt'"
AllowMsg = '{{.NameFirst}} {{.NameLast}} can receive {{.ShirtSize}} t-shirt'
DenyMsg = '{{.NameFirst}} {{.NameLast}} did not order a t-shirt'
DuplicateMsg = '{{.NameFirst}} {{.NameLast}} already received their {{.ShirtSize}} t-shirt {{.MinutesAgo}} minutes ago'
