[[Printers]]
Name = 'Bluebonnet'
Ip = '10.128.100.49'

[[Printers]]
Name = 'Acacia'
Ip = '10.128.100.41'

[[Printers]]
Name = 'Carnation'
Ip = '10.128.100.35'

[[Printers]]
Name = 'Echinacea'
Ip = '10.128.100.39'

[[Printers]]
Name = 'Daffodil'
Ip = '10.128.100.104'
